### ISSUE TITLE
Terminar PD-46 una vez exista listado de incidentes

### ISSUE THREAD

**Issue by fmoreyra** [tesis-cabal-cugno-moreyra/webapp#55]
PD-46: Pantalla donde se podrán cargar datos detallados del incidente (detalladas en la HU). Revisar la incorporación de mapa o buscador.
Se van a crear ramas particulares para cada una de estas tareas, que se van a mergear en la rama 040_create_incident.

Esta tarea está realizada, pero había quedado pendiente el listado de incidentes para terminarla.

**Comment by Gnoq** [comment]
close #40 
Este ticket el último step del flujo de la creación del incidente.
